# Generated by Django 6.0.5 on 2026-05-22 09:40

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/registry/secure-media/', location=pathlib.PureWindowsPath('C:/Users/Sheynyuy/Downloads/year 1 2nd/Python/Consensus/media_secure')), upload_to='photos/%Y/%m/%d/'),
        ),
    ]
