# Generated by Django 6.0.5 on 2026-05-31 23:47

import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_citizen_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdeclaration',
            name='father_national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='birthdeclaration',
            name='mother_national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOCKOUT', 'Account Locked')], max_length=20),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='father_national_id',
            field=registry.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='birthdeclaration',
            name='mother_national_id',
            field=registry.models.EncryptedCharField(max_length=255),
        ),
    ]
