# Generated by Django 6.0.5 on 2026-06-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_encrypt_declaration_nics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOCKOUT', 'Account Locked'), ('MFA_VERIFY', 'MFA Verified'), ('MFA_FAILED', 'MFA Failed')], max_length=20),
        ),
    ]
