# Generated by Django 6.0.5 on 2026-07-10 03:22

import django.db.models.deletion
import registry.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_populate_cameroon_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('husband_first_name', models.CharField(max_length=100)),
                ('husband_last_name', models.CharField(max_length=100)),
                ('husband_dob', models.DateField()),
                ('husband_national_id', registry.models.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('husband_national_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('wife_first_name', models.CharField(max_length=100)),
                ('wife_last_name', models.CharField(max_length=100)),
                ('wife_dob', models.DateField()),
                ('wife_national_id', registry.models.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('wife_national_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('date_of_marriage', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=150)),
                ('marriage_type', models.CharField(choices=[('MONOGAMOUS', 'Monogamous / Monogame'), ('POLYGAMOUS', 'Polygamous / Polygame')], default='MONOGAMOUS', max_length=20)),
                ('witness_1_name', models.CharField(max_length=200)),
                ('witness_2_name', models.CharField(max_length=200)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('husband_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_as_husband', to='registry.citizen')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marriage_registrations', to='registry.subdivision')),
                ('wife_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriages_as_wife', to='registry.citizen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
