# Generated by Django 6.0.5 on 2026-07-10 03:45

import django.db.models.deletion
import registry.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_marriage_registration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivorceDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ex_husband_first_name', models.CharField(max_length=100)),
                ('ex_husband_last_name', models.CharField(max_length=100)),
                ('ex_husband_national_id', registry.models.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('ex_husband_national_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('ex_wife_first_name', models.CharField(max_length=100)),
                ('ex_wife_last_name', models.CharField(max_length=100)),
                ('ex_wife_national_id', registry.models.EncryptedCharField(blank=True, max_length=255, null=True)),
                ('ex_wife_national_id_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('court_name', models.CharField(help_text='Name of the court that issued the divorce decree', max_length=200)),
                ('judgment_number', models.CharField(help_text='Court judgment / arrêt number', max_length=100)),
                ('date_of_divorce', models.DateField(help_text='Date the court decree was issued')),
                ('date_of_marriage', models.DateField(blank=True, help_text='Date of the original marriage (if known)', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('ex_husband_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divorces_as_husband', to='registry.citizen')),
                ('ex_wife_citizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divorces_as_wife', to='registry.citizen')),
                ('marriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divorce_declarations', to='registry.marriageregistration')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed', to=settings.AUTH_USER_MODEL)),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divorce_declarations', to='registry.subdivision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
