# Generated by Django 6.0.5 on 2026-05-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='citizen_profile',
            field=models.OneToOneField(blank=True, help_text='Linked citizen profile for Citizen users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='registry.citizen'),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Assigned division (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division_admins', to='registry.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Assigned region for Regional Admins.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_admins', to='registry.region'),
        ),
        migrations.AddField(
            model_name='user',
            name='subdivision',
            field=models.ForeignKey(blank=True, help_text='Assigned subdivision (Council) for Council Officers & Hospital Staff.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivision_users', to='registry.subdivision'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
