# Generated by Django 6.0.5 on 2026-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dr_incharge',
            field=models.CharField(blank=True, help_text='Name of the Doctor in charge.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital_type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], help_text='Hospital type (Government or Private).', max_length=50, null=True),
        ),
    ]
