"""
Django settings for clvrs_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import logging.handlers
from pathlib import Path
import environ
from django.core.exceptions import ImproperlyConfigured

_TESTING = 'test' in sys.argv

# Initialize environ — defaults are safe-for-production values
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),          # empty = safe default, must be set explicitly
    SESSION_COOKIE_SECURE=(bool, True),
    CSRF_COOKIE_SECURE=(bool, True),
    SECURE_SSL_REDIRECT=(bool, True),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file if it exists
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env('ALLOWED_HOSTS')

# Render sets RENDER_EXTERNAL_HOSTNAME automatically — allow it without manual config
if _render_host := os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(_render_host)

# Railway sets RAILWAY_PUBLIC_DOMAIN automatically
if _railway_host := os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(_railway_host)

# Railway healthcheck probe sends Host: healthcheck.railway.app
ALLOWED_HOSTS.append('healthcheck.railway.app')

# CSRF must trust the HTTPS origin that the platform terminates SSL on
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_host}')
if _railway_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_host}')

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',  # must be before staticfiles
    'django.contrib.staticfiles',
    
    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'axes',
    'anymail',
    
    # Local apps
    'accounts.apps.AccountsConfig',
    'registry.apps.RegistryConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Custom Security Headers Middleware
    'registry.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'clvrs_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clvrs_project.wsgi.application'

# Database Configuration
DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Douala'  # Cameroon's timezone
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
# In production, whitenoise serves pre-compressed, fingerprinted static files.
# In development, Django's built-in server handles statics directly from STATICFILES_DIRS.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG else
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# Media Files - Standard public uploads
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Secure Media Files (for sensitive photo uploads, stored outside standard media root)
SECURE_MEDIA_ROOT = BASE_DIR / 'media_secure'

# ── Cookie & session security ──
# In DEBUG mode cookies cannot be Secure (no HTTPS locally).
# In production these must all be True — enforced via .env.
SESSION_COOKIE_SECURE = False if DEBUG else env.bool('SESSION_COOKIE_SECURE', default=True)
CSRF_COOKIE_SECURE    = False if DEBUG else env.bool('CSRF_COOKIE_SECURE',    default=True)
SECURE_SSL_REDIRECT   = False if DEBUG else env.bool('SECURE_SSL_REDIRECT',   default=True)

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY    = True
SESSION_COOKIE_AGE      = 1800   # 30-minute idle timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE    = 'Strict'

# ── Transport security ──
# Render terminates SSL at the load balancer and forwards HTTP with X-Forwarded-Proto: https.
# Without this, SECURE_SSL_REDIRECT causes an infinite redirect loop on Render.
SECURE_PROXY_SSL_HEADER        = None if DEBUG else ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS            = 0 if DEBUG else 31536000   # 1 year in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD            = not DEBUG

# ── SSL redirect exemptions ──
# Railway healthcheck probes use plain HTTP — exempt /health/ so it gets 200
# instead of being redirected to HTTPS (which Railway doesn't follow).
SECURE_REDIRECT_EXEMPT = [r'^health/$']

# ── Content security ──
X_FRAME_OPTIONS          = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
# SECURE_BROWSER_XSS_FILTER is intentionally omitted — the header is deprecated
# and has no effect on modern browsers. Rely on CSP instead.
SECURE_REFERRER_POLICY   = 'strict-origin-when-cross-origin'

# ── Upload limits ──
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB maximum request body
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB maximum single file

# ── Activation token expiry (12 hours) ──
PASSWORD_RESET_TIMEOUT = 43200

# ── MFA OTP expiry (10 minutes) ──
MFA_OTP_EXPIRY_SECONDS = 600

# Crispy Forms Config
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Encryption Configuration
ENCRYPTION_KEY = env('ENCRYPTION_KEY')

# ── Email ──
# In production (Render/Railway) SMTP ports are blocked at the kernel level.
# Set BREVO_API_KEY in the hosting dashboard to route via Brevo's HTTPS API.
# Locally (no BREVO_API_KEY), falls back to direct SMTP for dev convenience.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='CLVRS Registry <noreply@clvrs.cm>')
_brevo_api_key = env('BREVO_API_KEY', default='')
if _brevo_api_key:
    EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
    ANYMAIL = {'BREVO_API_KEY': _brevo_api_key}
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = env.int('EMAIL_PORT', default=587)
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
    EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
    EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', default=30)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# ── Authentication backends ──
# AxesStandaloneBackend must come first so locked accounts are rejected
# before ModelBackend even checks the password.
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ── django-axes (per-account brute-force lockout) ──
from datetime import timedelta
AXES_FAILURE_LIMIT       = 5               # lock after 5 consecutive failures
AXES_COOLOFF_TIME        = timedelta(minutes=30)  # auto-unlock after 30 min
AXES_RESET_ON_SUCCESS    = True            # clear failure count on successful login
AXES_LOCKOUT_PARAMETERS  = ['username', 'ip_address']  # lock per username+IP pair
AXES_ENABLE_ADMIN        = True            # show locked accounts in Django admin
AXES_VERBOSE             = False

# ── Trusted reverse-proxy IPs ──
# Only connections from these IPs are allowed to set X-Forwarded-For.
# Set to your load-balancer / Nginx IP(s) in production, e.g. "10.0.0.1,10.0.0.2"
TRUSTED_PROXIES = set(env.list('TRUSTED_PROXIES', default=[]))

# ── Cache ──
# Tests always use LocMemCache (no Redis server required in CI or local dev).
# In production, Redis is required so rate limits survive across Gunicorn workers.
# In development (DEBUG=True), falls back to LocMemCache if REDIS_URL is not set.
_redis_url = env('REDIS_URL', default='')
if _TESTING or not _redis_url:
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": _redis_url,
            "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
            "KEY_PREFIX": "clvrs",
        }
    }

# ── Logging ──
LOG_DIR = BASE_DIR / 'logs'
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'clvrs.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'registry': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

